application: epricetracker
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /static
  static_dir: static

- url: /.*
  script: main.py

libraries:
- name: django
  version: "1.2"
