application: epricetracker
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /stylesheets
  static_dir: src/stylesheets

- url: /static
  static_dir: src/static

- url: /
  script: main.py

libraries:
- name: django
  version: "1.2"
